@baseAddress = http://localhost:5188
@categoryId=08ddb914-da6c-9453-345a-607b709e0000
@courseId=08ddc39e-54f4-f227-345a-607b709e0000

GET {{baseAddress}}/api/categories
Accept: application/json
###
GET {{baseAddress}}/api/categories/{{categoryId}}
Accept: application/json
###
POST {{baseAddress}}/api/categories
Accept: application/json
Content-Type: application/json
{
  "name": "New Kalem"
}
###
POST {{baseAddress}}/api/courses
Accept: application/json
Content-Type: application/json
{
  "name": "20256 New Kalem",
  "description": "Kalem kursu",
  "price": 100.0,
  "imageUrl": "https://example.com/image.jpg",
  "categoryId": "{{categoryId}}"
}
###
GET {{baseAddress}}/api/courses
Accept: application/json
###
GET {{baseAddress}}/api/courses/{{courseId}}
Accept: application/json
###