@baseAddress = http://localhost:5188
@categoryId=08ddb901-9d9b-5cfc-345a-607b709e0000

GET {{baseAddress}}/api/categories
Accept: application/json
###
GET {{baseAddress}}/api/categories/{{categoryId}}
Accept: application/json
###
POST {{baseAddress}}/api/categories
Accept: application/json
Content-Type: application/json
{
  "name": "New Kalem"
}
###
POST {{baseAddress}}/api/courses
Accept: application/json
Content-Type: application/json
{
  "name": "New Kalem",
  "description": "Kalem kursu",
  "price": 100.0,
  "imageUrl": "https://example.com/image.jpg",
  "categoryId": "{{categoryId}}"
}
###
