@baseAddress = http://localhost:5188
@categoryId=08ddc3b5-e399-dfd3-345a-607b709e0000
@courseId=08ddc3b5-fd8e-cddf-345a-607b709e0000

GET {{baseAddress}}/api/categories
Accept: application/json
###
GET {{baseAddress}}/api/categories/{{categoryId}}
Accept: application/json
###
POST {{baseAddress}}/api/categories
Accept: application/json
Content-Type: application/json
{
  "name": "telefon"
}
###
POST {{baseAddress}}/api/courses
Accept: application/json
Content-Type: application/json
{
  "name": "Iphone SE",
  "description": "En kucuk telefon",
  "price": 500,
  "imageUrl": "https://example.com/image.jpg",
  "categoryId": "{{categoryId}}"
}
###
GET {{baseAddress}}/api/courses
Accept: application/json
###
GET {{baseAddress}}/api/courses/{{courseId}}
Accept: application/json
###
PUT {{baseAddress}}/api/courses
Accept: application/json
Content-Type: application/json
{
  "Id": "{{courseId}}",
  "name": "Iphone 1",
  "description": "2026 yilinda piyasa surulecek telefon",
  "price": 44.0,
  "imageUrl": "https://example.com/image.jpg",
  "categoryId": "{{categoryId}}"
}
###
DELETE {{baseAddress}}/api/courses/{{courseId}}
Accept: application/json
###